### ISSUE TITLE
ServiceBus fails to start when using SimpleInjector.

### ISSUE THREAD

**Issue by nohros** [Shuttle/Shuttle.Core.SimpleInjector#2]
When using the SimpleInjector the container.Verify fails with the given message:

"The configuration is invalid. Creating the instance for type IMessageHandlerInvoker failed. Required dependency of type 'Shuttle.Core.Infrastructure.IComponentResolver' is null."

We are using the following configuration class:

```code
  internal class ConfigServiceBus : IConfigureComponent
  {
    public void Configure(Container container) {
      var shuttle_container = new SimpleInjectorComponentContainer(container);
      var config = ServiceBus.Register(shuttle_container);
    }
  }
```

The Configure method is called on process start using a code similar to:

```code
public class Program {
  public static void Main(string[] args) {
    var config = new ConfigServiceBus();
    config.Configure()
    container.Verify(); // An exception is raised here
  }
}
```

**Comment by eben-roux** [comment]
I added the `Verify` call in the `Shuttle.Idempotence` sample since it uses `SimpleInjector`.  It also fails...  I'll have to look into it.  However, it is rather odd that `IComponentResolver` is required since it shouldn't be in the container (if memory serves).

**Comment by eben-roux** [comment]
Ah... I see.

You will need to call the `Create` method on the `ServiceBus` as *that* sets the `IComponentResolver` instance on `DefaultPipelineFactory`.  I use this pattern since I don't want to register the resolver in the container.  It is a bit of a chicken-and-egg scenario in any event since you cannot register a service after a component has been resolved.

Im *my* case it was a matter of the `ControlInboxMessagePipeline` not being able to instantiate since it makes use of the `ConrolInbox` configuration object on the `IServiceBusConfiguration` instance and it simply isn't there.

I am going to guess that calling the `Verify` isn't going to always work since not all the registered services can actually be used.  Once again, it is going to be tricky to establish up-front what should and shouldn't be registered since it depends on configuration so everything is registered and only the bits that are used are actually instantiated.  The `Verify` seems to instantiate everything which leads to the errors that may not really manifest when running the code.

Let me know what you think.

**Comment by nohros** [comment]
Ok, I just removed the call to ```Verify```, the issue was resoved for SimpleInjector was resolved, now the Sql module is failing. I will open an issue on the SQL repository.

Thanks,
